### ISSUE TITLE
Strona demonstracyjna

### ISSUE THREAD

**Issue by SlimaKCoder** [SlimaKCoder/projectQ-Reloaded#5]
Pamiętam, że ktoś wspomniał coś o hostowaniu demonstracyjnej strony z projectQ-Reloaded. Kto ma odpowiedni hosting pod nią i chciałby się podjąć zarządzania i aktualizowania?

**Comment by Wruczek** [comment]
Ja mam stary, nieużywany hosting opłacony do czerwca 2016 r. Mogę pomóc :P

**Comment by SlimaKCoder** [comment]
W takim razie zostawiam to Tobie ;)
